---
- name: Construir imagen frontend
  community.docker.docker_image:
    build:
      path: /opt/app/apps/frontProducts
    name: frontend_app
    tag: latest

- name: Guardar imagen frontend en tar
  command: docker save frontend_app:latest -o /tmp/frontend.tar

- name: Importar imagen frontend en MicroK8s
  command: microk8s ctr image import /tmp/frontend.tar
