---
- name: Clonar repositorio frontend
  ansible.builtin.git:
    repo: "https://github.com/Daniout/Taller_Docker_Compose.git"
    dest: /opt/app/frontend
    version: ansible_docker_microk8s

- name: Construir imagen frontend
  ansible.builtin.command:
    cmd: docker build -t frontend:latest .
    chdir: /opt/app/frontend/apps/frontProducts

- name: Guardar imagen frontend en tar
  ansible.builtin.command:
    cmd: docker save frontend:latest -o /tmp/frontend-app.tar

- name: Importar imagen frontend en microk8s
  become: yes
  ansible.builtin.command:
    cmd: /snap/bin/microk8s ctr image import /tmp/frontend-app.tar
