---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Install base utilities
  apt:
    name:
      - git
      - curl
      - ca-certificates
      - apt-transport-https
      - gnupg
      - lsb-release
    state: present

- name: Add Docker GPG key (new method)
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /usr/share/keyrings/docker-archive-keyring.gpg
    mode: '0644'

- name: Add Docker repository
  ansible.builtin.apt_repository:
    # Use Debian 12 (bookworm) as Docker repo release since Debian 13 codename is not supported
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian bookworm stable"
    state: present

- name: Install Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes

- name: Ensure docker service is started
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Add user to docker group
  user:
    name: "{{ ansible_user | default('sysadmin') }}"
    groups: docker
    append: yes
