---
- name: Copy k8s manifests to remote
  copy:
    src: "{{ playbook_dir }}/../k8s/"
    dest: /home/{{ ansible_user | default('sysadmin') }}/k8s/
    owner: "{{ ansible_user | default('sysadmin') }}"
    mode: '0644'

- name: Apply k8s manifests (all)
  command: /snap/bin/microk8s kubectl apply -f /home/{{ ansible_user | default('sysadmin') }}/k8s/
  args:
    chdir: /home/{{ ansible_user | default('sysadmin') }}/k8s/
