---
- name: Clonar repositorio backend
  ansible.builtin.git:
    repo: "https://github.com/Daniout/Taller_Docker_Compose.git"
    dest: /opt/app/backend
    version: "ansible_docker_microk8s"
    update: yes
    force: yes

- name: Construir imagen backend
  community.docker.docker_image:
    build:
      path: /opt/app/backend
    name: backend
    tag: latest

- name: Guardar imagen backend como tar
  become: true
  ansible.builtin.command:
    cmd: docker save backend:latest -o /tmp/backend-app.tar

- name: Importar imagen backend en microk8s
  become: true
  ansible.builtin.command:
    cmd: /snap/bin/microk8s ctr image import /tmp/backend-app.tar
