---
- name: Clonar repositorio
  ansible.builtin.git:
    repo: "https://github.com/Daniout/Taller_Docker_Compose.git"
    dest: /opt/app
    version: ansible_docker_microk8s

- name: Construir imagen backend
  community.docker.docker_image:
    build:
      path: /opt/app/apps/backProducts
    name: backend_app
    tag: latest

- name: Guardar imagen backend en tar
  command: docker save backend_app:latest -o /tmp/backend.tar

- name: Importar imagen backend en MicroK8s
  command: microk8s ctr image import /tmp/backend.tar
