---
- name: Ensure remote app dir exists
  file:
    path: /home/{{ ansible_user | default('sysadmin') }}/apps/backProducts
    state: directory
    owner: "{{ ansible_user | default('sysadmin') }}"
    mode: '0755'

- name: Ensure rsync is installed on remote
  become: true
  apt:
    name: rsync
    state: present
    update_cache: yes

- name: Copy backend app to remote
  become: false   # run rsync locally without sudo
  delegate_to: localhost
  synchronize:
     src: "{{ playbook_dir }}/../apps/backProducts/"
     dest: "/home/{{ ansible_user | default('sysadmin') }}/apps/backProducts/"
     recursive: yes

- name: Build backend Docker image on remote
  command: docker build -t backend-app:latest /home/{{ ansible_user | default('sysadmin') }}/apps/backProducts
  args:
    chdir: /home/{{ ansible_user | default('sysadmin') }}/apps/backProducts

- name: Save backend image to tar
  command: docker save backend-app:latest -o /tmp/backend-app.tar

- name: Import backend image into microk8s (containerd)
  become: yes
  command: /snap/bin/microk8s ctr image import /tmp/backend-app.tar

- name: Ensure remote k8s dir exists
  file:
    path: /home/{{ ansible_user | default('sysadmin') }}/k8s
    state: directory
    owner: "{{ ansible_user | default('sysadmin') }}"
    mode: '0755'
