---
- name: Clonar repositorio backend
  ansible.builtin.git:
    repo: "https://github.com/tuusuario/tu-repo.git"
    dest: /opt/app/backend
    version: main

- name: Construir imagen backend
  ansible.builtin.command:
    cmd: docker build -t backend:latest .
    chdir: /opt/app/backend

- name: Guardar imagen backend como tar
  ansible.builtin.command:
    cmd: docker save backend:latest -o /tmp/backend-app.tar

- name: Importar imagen backend en microk8s
  become: yes
  ansible.builtin.command:
    cmd: /snap/bin/microk8s ctr image import /tmp/backend-app.tar
